version: '3.1'

services:
  app:
    image: 'example-rest-api-app'
    container_name: app
    expose:
      - '8080'
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      DB_USER: pavel
      DB_PASSWORD: password
      DB_URL: jdbc:postgresql://db:5432/postgres
#    entrypoint:
#      - DB_USER=pavel
#      - DB_PASSWORD=password
#      - DB_URL=jdbc:postgresql://db:5434/postgres
  db:
    image: 'postgres'
    container_name: db
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: pavel
      POSTGRES_PASSWORD: password
    expose:
      - '5434'
#    entrypoint:
#      - POSTGRES_USER=pavel
#      - POSTGRES_PASSWORD=password